name = "IMEXRungeKutta"
uuid = "6f46d5f7-e15e-41aa-a098-eed9d1a63ad8"
version = "1.1.0"
authors = ["Erik Schnetter <schnetter@gmail.com>"]

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"

[compat]
CommonSolve = "0.2.14"
julia = "1.10"
